### ISSUE TITLE
Error Occurs While Creating New Lucene Index in Kentico Admin Panel: 'Something went wrong! We have encountered an unexpected error

### ISSUE THREAD

**Issue by Rahul-Patel-17** [Kentico/xperience-by-kentico-lucene#73]
**Describe the bug**
An unhandled exception occurs while executing a request, failing to proxy a local development server. The error happens when the application attempts to proxy the request to http://localhost:3009/entry.js, but the connection is actively refused by the target machine. This suggests that the target server (localhost:3009) is either not running or inaccessible.

**To Reproduce**
1. Open the Kentico Admin Panel.
2. Go to Search under the Development section.
3. Navigate to the List of registered Lucene indices.
4. While creating a new index, the system will show an error message: "Something went wrong! We have encountered an unexpected error."
5. After this, you will be able to see the detailed error in the event log, including the message: No connection could be made because the target machine actively refused it. (localhost:3009).

**Expected behavior**
The system should allow the creation of a new Lucene index without encountering an error, and the proxy request to the target server (localhost:3009) should succeed.

**Library Version**
Kentico.Xperience.Lucene Version="6.0.0"
kentico.xperience.admin Version="29.3.0"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 128.0.6613.138 (Official Build) (64-bit)

**Additional context**
An unhandled exception has occurred while executing the request.
Message: Failed to proxy the request to http://localhost:3009/entry.js, because the request to the proxy target failed. Check that the proxy target server is running and accepting requests to http://localhost:3009/.

The underlying exception message was 'No connection could be made because the target machine actively refused it. (localhost:3009)'.Check the InnerException for more details.

Exception type: System.Net.Http.HttpRequestException
Stack trace:
at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
at Kentico.Xperience.Admin.Base.AdminLocalizationMiddleware.InvokeAsync(HttpContext context)
at Kentico.Content.Web.Mvc.WebsiteChannelContextMiddleware.InvokeAsync(HttpContext context, IWebsiteChannelContext websiteChannelContext)
at Kentico.Web.Mvc.KenticoRequestEventsMiddleware.InvokeAsync(HttpContext context)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Kentico.Web.Mvc.KenticoErrorHandlingMiddleware.InvokeAsync(HttpContext context, ILogger`1 logger)
at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

Message: No connection could be made because the target machine actively refused it. (localhost:3009)

Exception type: System.Net.Http.HttpRequestException
Stack trace:
at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionWithTelemetryAsync(HttpRequestMessage request, HttpConnectionPool pool, Boolean async, CancellationToken requestCancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)

Message: No connection could be made because the target machine actively refused it.

Exception type: System.Net.Sockets.SocketException
Stack trace:
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)

**Comment by seangwright** [comment]
You need to run the [DancingGoat client npm scripts](https://docs.kentico.com/developers-and-admins/customization/extend-the-administration-interface/prepare-your-environment-for-admin-development#choose-how-to-serve-client-scripts) when running the example app locally.

We should probably add this information (or link to the official docs) in [Contributing-Setup.md](https://github.com/Kentico/xperience-by-kentico-lucene/blob/v9.0.0/docs/Contributing-Setup.md).

**Comment by Rahul-Patel-17** [comment]
**Request for Comprehensive Search Implementation Documentation in Dancing Goat Example**

Could you please create proper documentation that outlines all the steps for implementing search functionality in the Dancing Goat example, similar to the detailed steps provided for creating a sample site using Xperience by Kentico? Having a step-by-step guide would greatly assist in ensuring consistency and ease of use during the implementation process.

Thanks in advance!

**Comment by seangwright** [comment]
> Could you please create proper documentation that outlines all the steps for implementing search functionality in the Dancing Goat example

Like [the detailed usage guide](https://github.com/Kentico/xperience-by-kentico-lucene/blob/main/docs/Usage-Guide.md) we have in the repository documentation?

**Comment by Rahul-Patel-17** [comment]
I would like to refer to a sample in the [documentation for Xperience by Kentico](https://docs.kentico.com/developers-and-admins/installation). While it provides some explanations and step-by-step guidance, I found that the [example mentioned above](https://github.com/Kentico/xperience-by-kentico-lucene/blob/main/docs/Usage-Guide.md) lacks clarity. If possible, could you please provide a detailed step-by-step breakdown? I would greatly appreciate your assistance!

**Comment by seangwright** [comment]
I don't think it's likely we will add documentation to <docs.kentico.com> for our open-source integrations because these integrations are updated at a different cadence than Xperience by Kentico. We would prefer to co-locate them in the repo.

All of our open-source integrations follow the same conventions - they have a top level `/docs` folder with a `Usage-Guide.md` file. The documentation is typically updated in the same PR as the library code if there are any functional changes (like an API breaking change).

However, we can definitely improve the instructions here. Which area of the Usage Guide lacks clarity? How would you like to see the information improved?
